### ISSUE TITLE
Mayusculas no admitidas en las opciones de respuesta

### ISSUE THREAD

**Issue by s-Woq** [alexbarretoz/Trivia-Geografia-General#2]
Intente poner la respuesta en mayuscula  y me tira un error
![image](https://user-images.githubusercontent.com/113298824/190038769-68524a7c-0556-4d37-82de-9211f6769c34.png)

**Comment by alexbarretoz** [comment]
![Captura de pantalla (252)](https://user-images.githubusercontent.com/113317048/190326898-4893c843-6841-4504-9b90-0eb46f3f0eb1.png)
He agregado un .lower( ) en el input de las respuestas, permitiendo colocar Mayúsculas.
